//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusStops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BusStops()
        {
            this.GuzergahDurak = new HashSet<GuzergahDurak>();
        }
    
        public int Id { get; set; }
        public string Durak_Adi { get; set; }
        public string Enlem { get; set; }
        public string Boylam { get; set; }
        public int Status { get; set; }
        public string Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuzergahDurak> GuzergahDurak { get; set; }
    }
}
