//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Busses
    {
        public int Id { get; set; }
        public string Plaka_No { get; set; }
        public int Bus_Selection { get; set; }
        public int Status { get; set; }
        public string Date { get; set; }
    }
}
