//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public long TC { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Bus_Selection { get; set; }
        public Nullable<int> Status { get; set; }
        public string Date { get; set; }
    }
}
