//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuzergahDurak
    {
        public int GuzergahDurak_Id { get; set; }
        public Nullable<int> Guzergah_Id { get; set; }
        public Nullable<int> Id { get; set; }
        public int Siralama { get; set; }
    
        public virtual BusStops BusStops { get; set; }
        public virtual Guzergah Guzergah { get; set; }
    }
}
